In [1]:
my_list =[1,2,3]

In [5]:
import numpy as np

In [9]:
arr = np.array (my_list)

In [11]:
arr

array([1, 2, 3])

In [13]:
my_array = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
my_array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
twodarray =np.array(my_array)

In [23]:
twodarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [29]:
np.zeros(3)

array([0., 0., 0.])

In [31]:
np.array((2,3))

array([2, 3])

In [33]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones(4)

array([1., 1., 1., 1.])

In [37]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [43]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.random.rand(5)

array([0.87691802, 0.44888202, 0.20887047, 0.25988232, 0.99595693])

In [47]:
np.random.rand(5,5)

array([[0.71610861, 0.35974189, 0.34823377, 0.01834323, 0.32558497],
       [0.33907184, 0.61134637, 0.60196802, 0.79263136, 0.21732608],
       [0.4915485 , 0.02731168, 0.38482278, 0.61468265, 0.24920606],
       [0.71648932, 0.62649914, 0.86670155, 0.6502192 , 0.96470326],
       [0.75324908, 0.05774455, 0.78537139, 0.78986154, 0.55914409]])

In [49]:
np.random.randn(3)

array([-0.25016154, -0.21851704, -0.48322377])

In [53]:
np.random.randint(1,100,10)

array([11, 98,  6, 96, 63,  8, 15, 20, 67,  4])

In [55]:
arr=np.arange(0,25)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
ranarr =np.random.randint(0,50,10)

In [61]:
ranarr

array([ 7, 26, 16, 37,  9, 36,  7, 14, 47, 13])

In [63]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
ranarr.max()

47

In [69]:
ranarr.min()

7

In [71]:
ranarr.argmax()

8

In [73]:
ranarr.argmin()

0

In [77]:
arr.shape

(25,)

In [79]:
arr=arr.reshape(5,5)

In [81]:
arr.shape

(5, 5)

In [85]:
arr.dtype

dtype('int32')

In [87]:
from numpy.random import randint

In [89]:
randint(2,10)

6

In [91]:
arr=np.arange(0,11)

In [93]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr[8]

8

In [97]:
arr[1:5]

array([1, 2, 3, 4])

In [99]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [101]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [103]:
arr[0:5]=100

In [105]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [109]:
arr = np.arange(0,11)

In [111]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
slice_of_array = arr[0:6]

In [115]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [117]:
slice_of_array[:]=99

In [119]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [121]:
arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [123]:
arr_copy=arr.copy()

In [125]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [127]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [129]:
arr_copy[:]=100

In [131]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [133]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [135]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [137]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [139]:
arr_2d[0,0]

5

In [145]:
arr_2d[0][0]

5

In [147]:
arr_2d[2][1]

40

In [149]:
arr_2d[1,2]

30

In [153]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [155]:
arr_2d[:1,:1]

array([[5]])

In [157]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [163]:
arr = np.arange(1,11)

In [165]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [167]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [169]:
bool_arr = arr>5

In [171]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [173]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [175]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [177]:
arr[arr<3]

array([1, 2])

In [179]:
arr_2d = np.arange(50).reshape(5,10)

In [181]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [187]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [189]:
arr_2d[3:,7:9]

array([[37, 38],
       [47, 48]])

In [193]:
import numpy as np

In [195]:
arr = np.arange(0,11)

In [197]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [199]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [201]:
arr -arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [203]:
arr *arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [205]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [207]:
arr *100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [209]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [211]:
1/0

ZeroDivisionError: division by zero

In [213]:
arr / arr

C:\Users\kpullagu\AppData\Local\Temp\ipykernel_55292\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [215]:
1 /arr

C:\Users\kpullagu\AppData\Local\Temp\ipykernel_55292\4127448963.py:1: RuntimeWarning: divide by zero encountered in divide
  1 /arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [217]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [219]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [221]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [224]:
np.max(arr)

10

In [226]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [228]:
np.log(arr)

C:\Users\kpullagu\AppData\Local\Temp\ipykernel_55292\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])